### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Animadversive** [adrianhajdin/project_shareme_social_media#3]
Amazing content. Best tut out there, and I followed it to the T (even cloned the repo) and I am still getting an error when signing into Google on the production build on a production site. This is what I see in the console: " Uncaught TypeError: Cannot read properties of undefined (reading 'name') " .

**Comment by chethanbhat** [comment]
I am facing the same error as well. Netlify app in production.

**Comment by chethanbhat** [comment]
Ok I found the solution. In responseGoogle function in Login.jsx and UserProfile.jsx use Google Client ID as template string

This will work -> clientId={`${process.env.REACT_APP_GOOGLE_API_TOKEN}`}
This won't work -> clientId={process.env.REACT_APP_GOOGLE_API_TOKEN}

This is because Google Client ID needs to be string according to the docs - https://www.npmjs.com/package/react-google-login

**Comment by Animadversive** [comment]
Thank you!
